
[non-housing_related]
	autogg_message = "gg"
	"&d&lautogg" = true

[settings]
	"&a&ltoggle_module" = true
	remove_asterisk = false
	name = "tdarth"
	chat_prefix = "&8[&b&lHousing&3Commands&8] &f"
	command = "thanks %player%"
	"&e&ltoggle_module" = true

[miscellaneous]
	"&5&lautoglhf" = true
	autogg_message = "goodgame"
	"&d&lautogg" = false
	autoglhf_message = "glhf"

[hc_commands]
	"&e&ltoggle_hc_commands" = true

[command_shortcuts]
	"&e&ltoggle_command_shortcuts" = true

[random_houses]
	custom_keyword = "PARKOUR"

[tools]
	"&cremove_asterisk" = false
	"&d&lchat_emojis" = true
	"&e&lremove_asterisk" = true
	remove_asterisk = false
	"&a&lremove_asterisk" = true
	"&a&lautowelcome" = true
	autowelcome_message = "o/ "

[misc]
	autogg_message = "gg"
	"&d&lautogg" = true

