
[non-housing_related]
	autogg_message = "gg"
	"&d&lautogg" = true

[settings]
	"&a&ltoggle_module" = true
	remove_asterisk = false
	name = "tdarth"
	chat_prefix = "&8[&b&lHousing&3Commands&8] &f"
	command = "thanks %player%"
	"&e&ltoggle_module" = true

[miscellaneous]
	"&5&lautoglhf" = false
	autogg_message = "ggasdas"
	"&d&lautogg" = true
	autoglhf_message = "glhf"

[hc_commands]
	"&e&ltoggle_hc_commands" = true
	discord_logger = true

[command_shortcuts]
	"&e&ltoggle_command_shortcuts" = true

[tools]
	"&cremove_asterisk" = false
	"&d&lchat_emojis" = true
	"&e&lremove_asterisk" = true
	remove_asterisk = false
	"&a&lremove_asterisk" = true

[misc]
	autogg_message = "gg"
	"&d&lautogg" = true

