
[settings]
	"&a&ltoggle_module" = true
	chat_prefix = "&8[&b&lHousing&3Commands&8] &f"
	command = "thanks %player%"
	"&e&ltoggle_module" = true

[hc_commands]
	"&e&ltoggle_hc_commands" = true
	discord_logger = true

[logger]
	webhook_link = ""
	discord_logger = false

[command_shortcuts]
	"&e&ltoggle_command_shortcuts" = true

